# Generated by Django 5.0.6 on 2024-05-30 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_staff_password_remove_staff_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='date_added',
        ),
        migrations.AddField(
            model_name='staff',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
