# Generated by Django 5.0.6 on 2024-05-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysales',
            old_name='quantity_sold',
            new_name='sell_quantity_products',
        ),
        migrations.AddField(
            model_name='dailysales',
            name='cost_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysales',
            name='description',
            field=models.TextField(blank=True, default='Note If Needed', null=True),
        ),
        migrations.AddField(
            model_name='dailysales',
            name='sell_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
