# Generated by Django 5.0.6 on 2024-05-31 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0002_rename_quantity_sold_dailysales_sell_quantity_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysales',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_management.store'),
        ),
        migrations.AddField(
            model_name='depositamount',
            name='Store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_management.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_management.store'),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='cost_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='sell_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
